#define TOUCH_TREE_NUM_STRIPS 4

#define TOUCH_TREE_LED_TYPE WS2812B             // WS2812B LED strips are used
#define TOUCH_TREE_COLOR_ORDER GRB              // WS2812B LED strips have GRB color order
#define TOUCH_TREE_DEFAULT_BRIGHTNESS 64        // TBD what is the range is 64 max?

#define TOUCH_TREE_CYCLE_INTERVAL 100 // 41.666 == 24 update / sec

#define TOUCH_TREE_SENSE1_NUM_LEDS CONFIG_SENSE1_NUM_LEDS
#define TOUCH_TREE_SENSE2_NUM_LEDS CONFIG_SENSE2_NUM_LEDS
#define TOUCH_TREE_SENSE3_NUM_LEDS CONFIG_SENSE3_NUM_LEDS
#define TOUCH_TREE_SENSE4_NUM_LEDS CONFIG_SENSE4_NUM_LEDS

#define TOUCH_TREE_PIN_TOUCH_SEND     CONFIG_PIN_TOUCH_SEND
#define TOUCH_TREE_SENSE1_PIN_RECEIVE CONFIG_SENSE1_PIN_RECEIVE
#define TOUCH_TREE_SENSE1_PIN_LED     CONFIG_SENSE1_PIN_LED
#define TOUCH_TREE_SENSE2_PIN_RECEIVE CONFIG_SENSE2_PIN_RECEIVE
#define TOUCH_TREE_SENSE2_PIN_LED     CONFIG_SENSE2_PIN_LED
#define TOUCH_TREE_SENSE3_PIN_RECEIVE CONFIG_SENSE3_PIN_RECEIVE
#define TOUCH_TREE_SENSE3_PIN_LED     CONFIG_SENSE3_PIN_LED
#define TOUCH_TREE_SENSE4_PIN_RECEIVE CONFIG_SENSE4_PIN_RECEIVE
#define TOUCH_TREE_SENSE4_PIN_LED     CONFIG_SENSE4_PIN_LED

#define TOUCH_TREE_DEFAULT_ACTIVE_COLOR    CONFIG_ACTIVE_COLOR
#define TOUCH_TREE_DEFAULT_INACTIVE_COLOR  CONFIG_INACTIVE_COLOR
struct TouchTree {
    long lastCycleTimestamp;

    RunnerCluster      runnerCluster;
    LedLeaf ledLeaf[TOUCH_TREE_NUM_STRIPS];
    
    TouchTree();
    void setup();
    void loop(); 
};
